CREATE TABLE account (
    accountid VARCHAR(255) NOT NULL PRIMARY KEY,
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20),
    password VARCHAR(20)
);

CREATE TABLE meeting (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(20),
    data TEXT,
    summary_data TEXT,
    create_date TIMESTAMP,
    date VARCHAR(20),
    category VARCHAR(20),
    account_accountid VARCHAR(255),
    CONSTRAINT fk_meeting_account
        FOREIGN KEY (account_accountid) REFERENCES account (accountid)
);

CREATE TABLE schedule (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(20),
    data TEXT,
    date TEXT,
    time VARCHAR(5),
    account_accountid VARCHAR(255),
    CONSTRAINT fk_schedule_account
        FOREIGN KEY (account_accountid) REFERENCES account (accountid)
);
