spring:
  datasource:
    url: jdbc:h2:mem:transmate-local;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false

transmate:
  auth:
    enabled: false
