spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
      path: /h2-console
      settings:
        web-allow-others: ${H2_CONSOLE_ALLOW_OTHERS:false}

transmate:
  aws:
    translate:
      region: ${AWS_TRANSLATE_REGION:ap-northeast-2}
